import PDFDocument from 'pdfkit';
import { rupees } from '../utils/money.js';
import { policyStatusAt } from './lifecycle.js';

export function streamPolicyPdf(policy, res) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${policy.policyNumber}.pdf"`);
  doc.pipe(res);
  const cfg = policy.termsSnapshot;
  doc.fillColor('#0b5ed7').fontSize(20).text('Vision Health Care', { continued: false });
  doc.fillColor('#555').fontSize(10).text('Policy Schedule (sample document — fictional product)');
  doc.moveDown();
  const row = (k, v) => doc.fillColor('#222').fontSize(11).text(`${k}: `, { continued: true }).fillColor('#000').text(String(v ?? '-'));
  row('Policy number', policy.policyNumber);
  row('Plan', `${policy.planName} (${policy.planCode}, terms version ${policy.planVersion})`);
  row('Policyholder', policy.holderName);
  row('Status', policyStatusAt(policy));
  row('Coverage period', `${policy.startDate} to ${policy.endDate}`);
  if (policy.product === 'health') {
    row('Sum insured', rupees(policy.coverage) + (policy.planType === 'floater' ? ' (shared family floater)' : ''));
    row('Annual premium', rupees(policy.annualPremium));
    row('Continuity start date', policy.continuityStartDate);
    doc.moveDown().fontSize(13).fillColor('#0b5ed7').text('Insured members');
    for (const m of policy.members) doc.fontSize(10).fillColor('#000').text(`• ${m.fullName} — ${m.relationship}, DOB ${m.dob}`);
    doc.moveDown().fontSize(13).fillColor('#0b5ed7').text('Key terms');
    doc.fontSize(10).fillColor('#000')
      .text(`Initial waiting period: ${cfg.initialWaitingDays} days`)
      .text(`Deductible per claim: ${rupees(cfg.deductiblePerClaim)}; Co-payment: ${cfg.copayBp / 100}%`)
      .text(`Room rent limit: ${rupees(cfg.roomRentLimitPerDay)} per day`)
      .text(`Condition waiting periods: ${(cfg.conditionWaitingPeriods || []).map((w) => `${w.condition} ${w.days}d`).join(', ')}`)
      .text(`Exclusions: ${(cfg.exclusions || []).map((e) => e.label).join('; ')}`);
  } else {
    row('Life assured', `${policy.lifeAssured.fullName} (DOB ${policy.lifeAssured.dob})`);
    row('Sum assured', rupees(policy.sumAssured));
    row('Policy term / premium payment term', `${policy.policyTerm} / ${policy.premiumPaymentTerm} years`);
    row('Premium', `${rupees(policy.installmentPremium)} ${policy.frequency} (annualised base ${rupees(policy.annualPremium)})`);
    row('Grace period', `${policy.graceDays} days`);
    row('Riders', policy.riders.join(', ') || 'None');
    const nom = policy.nomineeVersions.find((v) => v.status === 'effective');
    doc.moveDown().fontSize(13).fillColor('#0b5ed7').text('Nominees (current)');
    for (const n of nom?.nominees || []) doc.fontSize(10).fillColor('#000').text(`• ${n.name} — ${n.relationship}, ${n.sharePct}%${n.isMinor ? ` (guardian: ${n.guardian?.name})` : ''}`);
    doc.moveDown().fontSize(9).fillColor('#555').text('A nominee designation does not by itself authorise payment; all claims are subject to verification.');
  }
  doc.moveDown(2).fontSize(8).fillColor('#777').text('This document is generated by a demonstration system. All products, rates and data are fictional.');
  doc.end();
}
